//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test
    {
        public int id { get; set; }
        public string project_code { get; set; }
        public string username { get; set; }
        public string name { get; set; }
        public string form_name { get; set; }
        public Nullable<bool> View { get; set; }
        public Nullable<bool> Delete { get; set; }
        public Nullable<bool> Create { get; set; }
        public Nullable<bool> Print { get; set; }
        public Nullable<bool> Edit { get; set; }
        public Nullable<bool> All { get; set; }
        public int status { get; set; }
    }
}
